package:
  name: vtk-m-cuda
  version: "v1.3.0"

source:
  url: https://gitlab.kitware.com/vtk/vtk-m/repository/v1.3.0/archive.tar.bz2

requirements:
  build:
    - {{ compiler('cxx')}}
    - cmake
    - ninja

about:
  home: https://gitlab.kitware.com/vtk/vtk-m
  license: BSD 3-Clause
  license_file: LICENSE.txt
